### ISSUE TITLE
cannot load such file -- ffi (LoadError)

### ISSUE THREAD

**Issue by aurels** [thomasjachmann/launchpad#2]
Hi,

I get this when running the simple example.  Which Ruby version should I use ?

Thanks,

Aurélien

**Comment by thomasjachmann** [comment]
This is a [duplicate](https://github.com/thomasjachmann/launchpad/issues/1). You need to install the ffi gem.

**Comment by thomasjachmann** [comment]
Concerning your ruby version question: Both 1.8.7 and 1.9.3 work, although the tests won't run on 1.9.3 yet since I haven't worked on the project for quite some time now.

**Comment by aurels** [comment]
Thanks.
