### ISSUE TITLE
Outer buttons

### ISSUE THREAD

**Issue by ghost** [thomasjachmann/launchpad#6]
Does the library currently support the side buttons outside the main grid? Is there any plans to add it?

**Comment by LeeXGreen** [comment]
It does -- see https://github.com/thomasjachmann/launchpad/blob/master/examples/feedback.rb:

``` ruby
# red feedback for top control buttons
interaction.response_to([:up, :down, :left, :right, :session, :user1, :user2, :mixer]) do |interaction, action|
  interaction.device.change(action[:type], :red => brightness(action))
end
```

On the original launchpad, these are the buttons above the grid.

**Comment by thomasjachmann** [comment]
I need to get notifications for new issues here sorted out. Sorry for not answering so long, but fortunately, @LeeXGreen filled in. Thanks for that. Also have a look at https://github.com/thomasjachmann/launchpad/blob/16c775b1e5b66ffb57b87edcb0aed1b716c799b8/lib/launchpad.rb for the complete type list. There are also `:scene1` to `:scene8` for the buttons on the right side of the grid.

**Comment by thomasjachmann** [comment]
Closing this since I think this should be answered.
